# Shadowrocket: 2026-07-12 02:37:27
[General]
prefer-ipv6 = true
ipv6 = true
dns-direct-system = false

# --- 1. 隐私与解析设置  ---

# 开启私有 IP 应答，防止运营商 DNS 劫持
private-ip-answer = true
# --- WebRTC 隐私保护策略 ---
# 拦截并伪造 STUN 响应 IP，保护真实公网 IP 不泄露
stun-response-ip = 1.1.1.1
stun-response-ipv6 = ::1
# 旁路系统：解决推送延迟和系统更新问题
bypass-system = true
# 流量抓取白名单（局域网与部分Apple服务直连）
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
# TUN 模式排除网段
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.113.0.0/24, 224.0.0.0/4, fc00::/7, fe80::/10, ff00::/8
# 微软 DNS 与 DoH 加密
# 基础 DNS 解析：Microsoft DNS 与 Googe DNS
dns-server = 223.5.5.5
# 微软-谷歌 加密 DNS 接口
doh-server = https://edge.microsoft.com/dns-query, https://dns.google/dns-query, https://1.1.1.1/dns-query
